name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Git
        uses: actions/checkout@v2
      - name: Setup Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Run Unit Tests
        run: xcodebuild clean test -scheme NasaImage -destination platform=iOS\ Simulator,OS=14.4,name=iPhone\ 11 -derivedDataPath build | xcpretty
      - name: Convert Coverage
        run: bash coverage build/Logs/Test/*.xcresult/ > code-coverage.xml
      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: code-coverage.xml

  analyze:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
      - name: Sonar Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
